@baseUrl = http://localhost:3000/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkplZmZlcnNvbiIsImVtYWlsIjoiamVmZkBtYWlsLmNvbSIsImlhdCI6MTY4NjQ4MDk2MiwiZXhwIjoxNjg3MDg1NzYyLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMiJ9.7p_O6eTjynmTvWIJ1BLUfGxY7wvey0DCnVxfrgmeFY4

### LOGIN
POST {{baseUrl}}/login
Content-type: application/json

{
    "email": "jeff@mail.com",
    "password": "A123456"
}

### REGISTER
POST {{baseUrl}}/register
Content-type: application/json

{
    "name": "Fran",
    "email": "fran@mail.com",
    "password": "CC1234562"
}

### FORGET
POST {{baseUrl}}/forget
Content-type: application/json

{
    "email": "fran@mail.com",

}

### RESET
POST {{baseUrl}}/reset
Content-type: application/json

{
    "password": "AA1234562",
    "token": "a.a.a"

}

### CHECK TOKEN
POST {{baseUrl}}/me
Authorization: Bearer {{token}}
