@baseUrl = http://localhost:3000/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkZyYW4iLCJlbWFpbCI6ImZyYW5AbWFpbC5jb20iLCJpYXQiOjE2ODY0NTA0NDIsImV4cCI6MTY4NzA1NTI0MiwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjQifQ.ckeq1kuA8V5cUcpPGB9k4-ZU4Fs1Ru_qikQPrKvbt_0

### LOGIN
POST {{baseUrl}}/login
Content-type: application/json

{
    "email": "fran@mail.com",
    "password": "CC123456"
}


### REGISTER
POST {{baseUrl}}/register
Content-type: application/json

{
    "name": "Fran",
    "email": "fran@mail.com",
    "password": "CC1234562"
}

### FORGET
POST {{baseUrl}}/forget
Content-type: application/json

{
    "email": "fran@mail.com",

}

### RESET
POST {{baseUrl}}/reset
Content-type: application/json

{
    "password": "AA1234562",
    "token": "a.a.a"

}

### CHECK TOKEN
POST {{baseUrl}}/me
Authorization: Bearer {{token}}
