@baseUrl = http://localhost:3000/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkplZmZlcnNvbiIsImVtYWlsIjoiamVmZkBtYWlsLmNvbSIsImlhdCI6MTY4NjQ4MDk2MiwiZXhwIjoxNjg3MDg1NzYyLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMiJ9.7p_O6eTjynmTvWIJ1BLUfGxY7wvey0DCnVxfrgmeFY4
### CREATE
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-type: application/json

{
    "name": "Jose",
    "email": "jose@mail.com",
    "password": "CC123456"
}

### GET ALL
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET BY ID
GET {{baseUrl}}/2
Authorization: Bearer {{token}}

### UPDATE ALL DATA
PUT {{baseUrl}}/2
Content-type: application/json

{
    "name": "Jefferson",
    "email": "jeff@mail.com",
    "password": "C123456"
}

### UPDATE PARTIAL
PATCH {{baseUrl}}/2
Authorization: Bearer {{token}}
Content-type: application/json

{
    "password": "A123456"
}

### DELETE
DELETE {{baseUrl}}/1

