@baseUrl = http://localhost:3000/users

### CREATE
POST {{baseUrl}}
Content-type: application/json

{
    "name": "Fran",
    "email": "fran@mail.com",
    "password": "CC123456"
}

### GET ALL
GET {{baseUrl}}

### GET BY ID
GET {{baseUrl}}/3

### UPDATE ALL DATA
PUT {{baseUrl}}/2
Content-type: application/json

{
    "name": "Jefferson",
    "email": "jeff@mail.com",
    "password": "C123456"
}

### UPDATE PARTIAL
PATCH {{baseUrl}}/4
Content-type: application/json

{
    "birth_at": "1993-08-05"
}

### DELETE
DELETE {{baseUrl}}/1

